{"componentChunkName":"component---src-templates-post-template-js","path":"/posts/i-learn-today-05-Jan-2021","result":{"data":{"markdownRemark":{"id":"7c7adbb7-f3f1-5608-9fb4-e7ba28de854a","html":"<h2 id=\"item-1\" style=\"position:relative;\"><a href=\"#item-1\" aria-label=\"item 1 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 1:</h2>\n<blockquote>\n<p>In Java, anything except primitives is <em>Object</em> and by that definition, <em>Exceptions</em> are _Objects. Exceptions indicate that some events that shouldn’t have happened (or intended) occurred in the system.  Broadly, there’re two exceptional events:    <strong>Exceptions and Errors</strong></p>\n<p><strong>Exceptions and Errors</strong> are sub-types of <strong>Throwable</strong></p>\n</blockquote>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">\t\tObject\n\t\t  |\n\t\t  |\n\t   Throwable\n\t     /  \\\n \t\t/    \\\n     Error   Exception\n\t \t</code></pre></div>\n<h2 id=\"item-2\" style=\"position:relative;\"><a href=\"#item-2\" aria-label=\"item 2 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 2:</h2>\n<blockquote>\n<p>Exceptions are handled by enclosing the expected code/block (that might throw exceptions) with <strong>try</strong> / <strong>catch or finally</strong> block. Either <strong>catch</strong> or <strong>finally</strong> (or <strong>both</strong>) is required following the <strong>try</strong> block. If both are missing following the <strong>try</strong> block, it’ll be a compilation issue.</p>\n</blockquote>\n<h2 id=\"item-3\" style=\"position:relative;\"><a href=\"#item-3\" aria-label=\"item 3 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 3:</h2>\n<blockquote>\n<p>There can be multiple <strong>catch block/clause</strong> following the <strong>try</strong> block. However, the order of <strong>catch clauses</strong> matter when they belong to parent/child relationships but not with siblings.</p>\n</blockquote>\n<p>What this implies is that, when a try block is followed by multiple <strong>catch clauses/blocks</strong>, and if they’re related to one another as Parent/Child hierarchy, then they should be arranged bottom up, with the most generic type at the bottom.</p>\n<p>Here is an example. Imagine A, B, C are types of Exception and A is the root of this relationship. If we need to catch an exception based on them, here’s what we need to layout -</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">\ttry {\n\t\t...\n\t\t...\n\t}\n\tcatch(C) {\n\t\t...\n\t}\n\tcatch(B) {\n\t\t...\n\t}\n\tcatch(A) {\n\t\t...\n\t}\n\tfinally {\n\t\t// code clean up\n\t}</code></pre></div>\n<p>If we reverse the layout with A being at the top, <strong>it will consume exceptions that belong to B and C</strong> and that doesn’t make sense. So, the compiler will throw a compilation problem.</p>\n<p><strong>However</strong>, this rule doesn’t apply when the exceptions are <em>siblings</em> to one another (not Parent/child type). In that situation, <strong>the order doesn’t matter</strong>.</p>\n<h2 id=\"item-4\" style=\"position:relative;\"><a href=\"#item-4\" aria-label=\"item 4 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 4:</h2>\n<blockquote>\n<p>All exceptions (excpept Runtime exceptions and errors) <strong>must be declared or handled</strong> otherwise, compilation issue will occur as Compiler checks as a rule of <strong>Checked Exception</strong></p>\n</blockquote>\n<p>Below example will throw a compilation issue -</p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">// inside a class\n\nfunction bar() {\n\tthrow new Exception();\n}\n\nfunction foo() {\n\tbar();\n}</code></pre></div>\n<p>However, either <em>declare</em> or <em>handle</em> shall avoid compilation issue.</p>\n<p><em>Case 1: Declaring an exception</em></p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">function bar() {\n\tthrow new Exception();\n}\n\nfunction foo() throws Exception {\n\tbar();\n}</code></pre></div>\n<p><em>Case 2: Handle an exception</em></p>\n<div class=\"gatsby-highlight\" data-language=\"text\"><pre class=\"language-text\"><code class=\"language-text\">function bar() {\n\tthrow new Exception();\n}\n\nfunction foo(){\n\ttry {\n\t\tbar();\n\t}\n\tcatch(Exception e) {\n\t\t...\n\t}\n\t\n}</code></pre></div>\n<h2 id=\"item-5\" style=\"position:relative;\"><a href=\"#item-5\" aria-label=\"item 5 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 5:</h2>\n<blockquote>\n<p>Finally clause, if present, runs regardless of whether an exception occurs or not.</p>\n</blockquote>\n<ul>\n<li>When exception doesn’t occur in <em>try block</em>, <em>finally</em> will run</li>\n<li>When exception occurs and handles in any of the <em>catch block</em>, <em>finally</em> will also (run after them)</li>\n<li>If there is a <em>return</em> statement inside <em>try/catch</em> block, <em>finally</em> will also run (before returning)</li>\n</ul>\n<p><em>However</em>, <em>the only condition when finally shall not run is when JVM shuts down. E.g. When there is a System.exit() invocation inside try/catch block, finally shall not be invoked</em></p>\n<h2 id=\"item-6\" style=\"position:relative;\"><a href=\"#item-6\" aria-label=\"item 6 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 6:</h2>\n<blockquote>\n<p>Runtime exceptions are never checked by compiler and hence called <strong>Unchecked exceptions</strong> E.g. <strong>Null Pointer Exception</strong>, <strong>Arithmetic Exception</strong>, <strong>ArrayIndexOfBoundException</strong> etc. - something that compiler can’t check/verify before the code is executed. </p>\n</blockquote>\n<p>In this case, the <em>handle or declare</em> rule <strong>is not applicable</strong>.</p>\n<h2 id=\"item-7\" style=\"position:relative;\"><a href=\"#item-7\" aria-label=\"item 7 permalink\" class=\"anchor before\"><svg aria-hidden=\"true\" focusable=\"false\" height=\"16\" version=\"1.1\" viewBox=\"0 0 16 16\" width=\"16\"><path fill-rule=\"evenodd\" d=\"M4 9h1v1H4c-1.5 0-3-1.69-3-3.5S2.55 3 4 3h4c1.45 0 3 1.69 3 3.5 0 1.41-.91 2.72-2 3.25V8.59c.58-.45 1-1.27 1-2.09C10 5.22 8.98 4 8 4H4c-.98 0-2 1.22-2 2.5S3 9 4 9zm9-3h-1v1h1c1 0 2 1.22 2 2.5S13.98 12 13 12H9c-.98 0-2-1.22-2-2.5 0-.83.42-1.64 1-2.09V6.25c-1.09.53-2 1.84-2 3.25C6 11.31 7.55 13 9 13h4c1.45 0 3-1.69 3-3.5S14.5 6 13 6z\"></path></svg></a>ITEM 7:</h2>\n<blockquote>\n<p><strong>Errors</strong> are not a subtype of Exception, they don’t need to be declared. You’re free to declare it if you like, but the compiler just doesn’t care one way or another when or how the Error is thrown or by whom.</p>\n</blockquote>","fields":{"slug":"/posts/i-learn-today-05-Jan-2021","tagSlugs":["/tag/java/"]},"frontmatter":{"date":"2021-01-05T06:09:25.475Z","description":"Java Exceptions 101","tags":["Java"],"title":"I learn today - Java Exceptions 101","socialImage":null}}},"pageContext":{"slug":"/posts/i-learn-today-05-Jan-2021"}}}